### ISSUE TITLE
Incorrect colors used in vim :terminal

### ISSUE THREAD

**Issue by marklawlor** [trevordmiller/nova-vim#115]
iTerm:  3.3.1, using Nova-iTerm colors. Bold is enabled
Vim: 8.1 (latest on Homebrew) using nova-vim

Colors in normal terminal:
![Screen Shot 2019-08-07 at 9 48 52 am](https://user-images.githubusercontent.com/3946701/62584586-9a33d880-b8f8-11e9-9c63-81c3d6f48733.png)

Colors when using :terminal in vim
![Screen Shot 2019-08-07 at 9 46 25 am](https://user-images.githubusercontent.com/3946701/62584503-3f9a7c80-b8f8-11e9-99af-21a9495b1ac5.png)

After a recent upgrade of both vim and iTerm, the colors in vim's :terminal are incorrect. It appears they are using the normal ASCI colors instead of the bright ASCI colors.

Issue still occurs on a new iTerm profile and using the example `.vimrc` file in this repo. Other themes are correctly correctly eg. nova-git and nova-tmux (but I'm not currently using tmux)

Let me know if you need anymore information

**Comment by trevordmiller** [comment]
@marklawlor To my knowledge, this has to do with iterm bold settings, not `nova-vim`. Since `nova-vim` is using the colors correctly:

https://github.com/trevordmiller/nova-vim/blob/4e117d23c55cf0e49e2f8eb4587c868ed91387bd/src/index.js#L419-L436

So I'm going to close this. But let me know if I'm misunderstanding something or if you have a pull request :)

**Comment by trevordmiller** [comment]
Per `:help terminal_ansi_colors`:

> "							*g:terminal_ansi_colors*
In GUI mode or with 'termguicolors', the 16 ANSI colors used by default in new
terminal windows may be configured using the variable
`g:terminal_ansi_colors`, which should be a list of 16 color names or
hexadecimal color codes, similar to those accepted by |highlight-guifg|.  When
not using GUI colors, the terminal window always uses the 16 ANSI colors of
the underlying terminal."

**Comment by marklawlor** [comment]
Thanks for responding. I initially thought it was iTerm as well, however :terminal is the only place the incorrect colours show. I believe my iterm is correctly configured as it displays bright bold colours everywhere else (see the second screen shot). I'm not sure what iTerm setting would only affect vim :terminal. 

I've run a couple of True Colour test bash/python scripts. They all pass showing all the true colors, including in :terminal. 

So I'm kind of stumped on this one. Should I cross poss this to the nova-iterm repo?

**Comment by trevordmiller** [comment]
@marklawlor No need to cross post to the nova-item repo. It does seem to be related to `:terminal`, but I don't know of a way around it since to my knowledge this is correct:

https://github.com/trevordmiller/nova-vim/blob/4e117d23c55cf0e49e2f8eb4587c868ed91387bd/src/index.js#L419-L436

If you figure out something, feel free to submit a PR for those lines ^ :)
