### ISSUE TITLE
Selected highlight isn't clear in iTerm

### ISSUE THREAD

**Issue by jacob-israel-turner** [trevordmiller/nova-vim#36]
Searching while using neovim in iTerm is significantly less convenient while using nova.  Here is how it looks using Nova:

![screen shot 2016-10-10 at 10 43 15 am](https://cloud.githubusercontent.com/assets/8698364/19243842/a4a07f52-8ed6-11e6-8dbe-542cc2366146.png)

While using another theme, it looks like this:
![screen shot 2016-10-10 at 10 44 09 am](https://cloud.githubusercontent.com/assets/8698364/19243853/b2e6a9e2-8ed6-11e6-8993-239086792880.png)

Cycling through my searches (`n`) is difficult.  I have to count to know which I have selected.

Highlighting appears to work properly in Hyper (though, it's still far more subtle than most color schemes), so I'm assuming this is an issue with iTerm.

**Comment by jacob-israel-turner** [comment]
This is how it looks in Hyper:
![screen shot 2016-10-10 at 10 48 23 am](https://cloud.githubusercontent.com/assets/8698364/19243934/27c5c892-8ed7-11e6-9436-9e0ebfb7334e.png)

It looks like I might have something wrong with my colors (`this` isn't colored in iTerm).

**Comment by trevordmiller** [comment]
Thanks for the feedback! I agree; I think search results should use `novaColors.uiGroups.userCurrentState` (cyan) as the foreground (text) and use a `novaColors.uiGroups.gray3` (light gray) for the background. Feel free to submit a pull request [using the "CONTRIBUTING" guidelines](https://trevordmiller.github.io/nova); otherwise, I'll get to this :)
