### ISSUE TITLE
Swap file message colors

### ISSUE THREAD

**Issue by aharris88** [trevordmiller/nova-vim#39]
It would be good to have this red and green use nova colors.

![screen shot 2016-10-11 at 12 55 12 pm](https://cloud.githubusercontent.com/assets/3266363/19284182/10827cc6-8fb2-11e6-9854-c847542c55bc.png)

**Comment by trevordmiller** [comment]
Thanks for the feedback! I agree. Feel free to submit a pull request [using the "CONTRIBUTING" guidelines](https://trevordmiller.github.io/nova); otherwise, I'll get to this :)

**Comment by trevordmiller** [comment]
Not sure what these highlight groups are called since I can't use my normal [vim-scriptease](https://github.com/tpope/vim-scriptease) cursor over or `:highlight` list...since this is already in the command line without access to these commands. Anyone know how to tell what highlight groups the red and green are here so we can update them to be `novaColors.uiGroups.userActionNeeded`?

**Comment by trevordmiller** [comment]
I'm closing this for now, since it is lower priority than other things I'm working on. Standard Vim uses the highlight group colors correctly, this is only a problem in Neovim. If anyone would like to re-open the issue and submit a pull request, let me know! I'd be happy to have your contribution :)
