### ISSUE TITLE
Cursor + Highlight = :-(

### ISSUE THREAD

**Issue by iammerrick** [trevordmiller/nova-vim#65]
Currently, the cursor settings and the highlighted word settings are the same which means when you are jumping around with `*` `n` `;` etc. you can't see your cursor. In this image, the cursor is actually on the "S"
![screen shot 2017-03-28 at 10 57 21 am](https://cloud.githubusercontent.com/assets/109635/24417373/5f22f99c-13a5-11e7-92de-efa647281daa.png)

**Comment by aharris88** [comment]
I might have it installed incorrectly or something, but here's how it looks to me.

![screen shot 2017-03-28 at 11 21 47 am](https://cloud.githubusercontent.com/assets/3266363/24418301/c590481c-13a8-11e7-83be-d4f28b5d18b2.png)

**Comment by trevordmiller** [comment]
@iammerrick 

This was introduced last week here:
https://github.com/trevordmiller/nova-vim/pull/63

I didn't see this as a problem since I use `set cursorline`, but I'm glad you noticed without cursor line. Ideally, Vim would have [a unique highlight group for the current item](https://github.com/trevordmiller/nova-vim/issues/61) so the colors could be updated, but it doesn't - so we have to use the same colors for any search result. So, how about we go back to how it was before https://github.com/trevordmiller/nova-vim/pull/63, with the lighter gray background and cyan text inside? That way you can see your cursor over matches again.

@aharris88 Your colors are off a bit; the background color looks brown, and your search highlight should be cyan instead of blue. Not sure why. This is what it looks like for me in Hyper + tmux + terminal regular Vim 8 with the settings from https://trevordmiller.com/projects/nova:
![image](https://cloud.githubusercontent.com/assets/5497885/24420844/74fbd91c-13b1-11e7-8aa8-10f9f2784dee.png)

**Comment by trevordmiller** [comment]
fyi @alnjxn

**Comment by iammerrick** [comment]
@trevordmiller man!  I loved this change until the cursor thing! I support whatever fix you think is best.

**Comment by iammerrick** [comment]
@aharris88 there is definitely something weird with your setup my friend. :-)

**Comment by aharris88** [comment]
@trevordmiller @iammerrick Yeah, I didn't have tmux true color turned on... Sorry for hijacking this thread. And the cursor was white because of the "Smart Cursor Color" setting in iTerm. I'm not sure why I'm missing the color on the line number or why my cursor is not as tall as the rest of the highlight...

![screen shot 2017-03-28 at 12 49 35 pm](https://cloud.githubusercontent.com/assets/3266363/24422021/57fd0d96-13b5-11e7-92a1-0a49f69cc9ac.png)

**Comment by trevordmiller** [comment]
@iammerrick Ok, I'll keep this issue open and tinker with it when I have time; I'll come up with something that works well.

@aharris88 No worries, glad you figured it out :)

**Comment by trevordmiller** [comment]
@aharris88 The cursor is controlled by your terminal emulator, not Vim - so sadly I have no control over that in nova-vim. As for the cursor line background highlight and number being highlighted, if you want that you need to add `set cursorline` to your vim config.
