### ISSUE TITLE
Support for Rainbow Parens

### ISSUE THREAD

**Issue by SevereOverfl0w** [trevordmiller/nova-vim#72]
Set default colours for:
- https://github.com/luochen1990/rainbow
- https://github.com/kien/rainbow_parentheses.vim
- http://www.vim.org/scripts/script.php?script_id=4580

Might be worth reviewing how [Gruvbox](https://github.com/morhetz/gruvbox) does it (https://github.com/morhetz/gruvbox/blob/c2c15907e96bed070259bfaf0faed3bc3db0e268/colors/gruvbox.vim#L696-L722)

**Comment by trevordmiller** [comment]
Hi @SevereOverfl0w, thank you for using Nova! Nova has dedicated color meanings for syntax, so it uses the "special" (orange) color for parenthesis:
![image](https://user-images.githubusercontent.com/5497885/27139979-a3730442-50e1-11e7-8a03-a4b18002ea8a.png)
I'd like to not add support for rainbow parens, since it goes against the dedicated color setup. However, feel free to fork the project for yourself and add support if you'd like :)

**Comment by trevordmiller** [comment]
@SevereOverfl0w The list of nova colors is here: https://github.com/trevordmiller/nova-colors/blob/master/src/index.js
It is used with Vim plugins in nova-vim like so: https://github.com/trevordmiller/nova-vim/blob/master/src/index.js#L84

Although if you want to use standard Nova, changing the parenthesis colors doesn't align with the project goals of having a dedicated color per syntax group so I'd recommend not adding this :)

**Comment by SevereOverfl0w** [comment]
Unfortunately the pragmatics of writing a Lisp mean that rainbow parens are a very useful tool for reading code.

I was wondering if there was a good way to modify them slightly in some axis (contrast or brightness or something else? I don't know colours!)  that would stop me from having them bump into each other.

Having said all this, I may try turn off rainbows for a while, and see if I miss them.

**Comment by trevordmiller** [comment]
@SevereOverfl0w Gotcha. Yeah, I'm not sure if contrast/opacity/brightness etc. can be tweaked, but feel free to fork and play around :)
