### ISSUE TITLE
Vim tabs are hard to read with the white background

### ISSUE THREAD

**Issue by maximmcnair** [trevordmiller/nova-vim#81]
Really love this theme! However I find the tabs hard read with the white background. I've tried with a stripped down vim.init to check it wasn't a conflict with another package.  My setup is iterm2 and neovim with both color schemes installed. 

```
" setup vim plug
call plug#begin('~/.config/nvim/plugged')
  Plug 'vim-airline/vim-airline'
  Plug 'trevordmiller/nova-vim'
call plug#end()

colorscheme nova
```

![screen shot 2017-09-13 at 14 14 42](https://user-images.githubusercontent.com/1009787/30379335-10996e1e-988e-11e7-882c-d16490d587fc.png)

**Comment by agarrharr** [comment]
Mine looks the same. I have to agree, that it's a bit hard to read on the light grey background. This is a low contrast color scheme, but this seems lower contrast than normal. I'm not sure what options we have here. @trevordmiller Is this something you've noticed? I don't use tabs a lot myself, so I didn't really notice.

**Comment by trevordmiller** [comment]
@maximmcnair Good catch, that is a bug I haven't noticed because I don't use Vim tabs either. This should be updated to match the other "toggle" styles across Nova:

![image](https://user-images.githubusercontent.com/5497885/30385788-6e590628-9865-11e7-83ce-20932800adb0.png)

So the tab bar background should be `uiGroups.backgroundShade`, with the foreground being `uiGroups.gray3` unless active then it should be `uiGroups.userCurrentState`.

If either of you want to submit a PR, go for it. Otherwise I'll get to this :)

Thanks for using Nova!

**Comment by trevordmiller** [comment]
Also of note, the Vim airline doesn't have the best contrast; here is what non-airline (native status bar) looks like:

![image](https://user-images.githubusercontent.com/5497885/30385871-9f015fc8-9865-11e7-863d-54e899c642f2.png)

We have discussed updating airline to match in https://github.com/trevordmiller/nova-vim/issues/75, but I left the decision to @alexlafroscia to keep it as is since he built it and I don't use airline; but the more I see it the more I think it should be updated with the `backgroundShade` setup like the native status bar. @alexlafroscia, would you be ok if I reopen that issue and make the change? I can take care of it since I know you are busy.

**Comment by maximmcnair** [comment]
Created a PR #82 to match above conversation
