### ISSUE TITLE
No colours when used as mergetool with vimdiff

### ISSUE THREAD

**Issue by codeinabox** [trevordmiller/nova-vim#83]
I've noticed that this colour scheme doesn't work when vim is used as git mergetool. My gitconfig contains this:

```
[diff]
	tool = vimdiff
[difftool]
	prompt = false
[merge]
	tool = vimdiff
```

When I run `git mergetool` to resolve a conflict there are no colours but if I use `colorscheme default` or other themes the colours display fine.

**Comment by trevordmiller** [comment]
@codeinabox Good catch. Thanks for using Nova and letting me know. Feel free to submit a PR if you'd like; otherwise I'll take care of this :)

**Comment by codeinabox** [comment]
I'll have to leave it in your capable hands as I don't know why it doesn't play nice with vimdiff or using vim as a man pager.

**Comment by gauravdesale** [comment]
I am interested in contributing to this but I dint know which file to look into. Is there any way for me to do so and get acquainted with the repo

**Comment by trevordmiller** [comment]
@gauravdesale Wonderful! I’d love to have your help. First, please read through the [CONTRIBUTING.md](https://github.com/trevordmiller/nova-vim/blob/master/CONTRIBUTING.md). Then, make code changes in [src/index.js](https://github.com/trevordmiller/nova-vim/blob/master/src/index.js). For this issue the changes will be in the “VERSION CONTROL” section; I haven’t tested this issue myself yet but my guess is there are some missing vimdiff highlight groups that need to be added (using the `versionControlGroups.added/modified/removed` values as the other version control highlight groups do). Does that make sense?

**Comment by trevordmiller** [comment]
@codeinabox I set up vimdiff and used `git mergetool` and this is what I was getting without any changes to nova-vim:

So it was working. I double checked the highlight groups being applied with `:hi` and they are indeed being applied:

<img width="1920" alt="screen shot 2017-10-09 at 3 55 54 pm" src="https://user-images.githubusercontent.com/5497885/31360151-5b9eea98-ad0a-11e7-9f0b-7d991118a312.png">

<img width="651" alt="screen shot 2017-10-09 at 3 42 44 pm" src="https://user-images.githubusercontent.com/5497885/31360017-a8bfe986-ad09-11e7-8444-74d11fe52ac0.png">

So I'm not sure why your setup isn't working; have you tried upgrading your vim + git etc.? Do you have any overridding styles in your .vimrc? As I was testing this, I did feel the background colors were hard to work with so I changed the colors to be on the text itself instead of the background in https://github.com/trevordmiller/nova-vim/pull/85, so it looks like this now (red for delete, orange for change, green for new):

<img width="1920" alt="screen shot 2017-10-09 at 3 47 55 pm" src="https://user-images.githubusercontent.com/5497885/31360018-a8cf2270-ad09-11e7-9c66-66fc8144839f.png">

![image](https://user-images.githubusercontent.com/5497885/31360309-f7a9c8a4-ad0a-11e7-9a66-079a05496e37.png)

But either way, you should see colors so something is up with your setup. Closing this issue.
