### ISSUE TITLE
Terminal Vim

### ISSUE THREAD

**Issue by jlconlin** [trevordmiller/nova-vim#89]
I love this color scheme, but I have some troubles when I use it in terminal Vim. I get the following error:

```
Error detected while processing /home/jlconlin/.vim/bundle/nova-vim/colors/nova.vim
E518: Unknown option: termguicolors
E518: Unknown option: termguicolors
```

I recognize this means that my version of Vim was not compiled with the gui option. Can we modify this color scheme to remove these errors and make it more applicable for terminal ViM?

**Comment by trevordmiller** [comment]
Hey @jlconlin, thanks! Nova is build for terminal Vim, but it requires Vim 8+ (which has the `termguicolors` option).

From the website:

<img width="792" alt="screen shot 2018-01-23 at 1 22 15 pm" src="https://user-images.githubusercontent.com/5497885/35298827-911c03c0-0040-11e8-8473-fa6d42c82820.png">

https://trevordmiller.com/projects/nova

Related closed issues: https://github.com/trevordmiller/nova-vim/issues?utf8=%E2%9C%93&q=is%3Aissue+termguicolors

So if you'll update to Vim 8 it will work. Nova requires Vim 8 because the True Color support makes the theme much more lightweight and better looking. I'm not interested in supporting Vim versions previous to Vim 8 to keep the code size smaller and incourage upgrading Vim.

Hope that helps :) Closing this issue.

**Comment by jlconlin** [comment]
Thanks, that does help. I suppose I should read the manual more closely.

**Comment by trevordmiller** [comment]
@jlconlin No problem :) If you are on mac OS, I recommend using [homebrew](https://brew.sh). So you can `brew install vim`, then `brew update && brew upgrade vim` in the future to stay up-to-date. Good luck!

**Comment by jlconlin** [comment]
Actually, on my Mac I don't have any problems as I use MacVim. It's when I'm on Linux that I have Vim 7.x.

**Comment by trevordmiller** [comment]
@jlconlin Ok so you need to `sudo apt-get update && sudo apt-get install vim` or related for another Linux package manager :)
