### ISSUE TITLE
No syntax highlighting after update

### ISSUE THREAD

**Issue by jlconlin** [trevordmiller/nova-vim#99]
I recently updated my plugins (I use Vundle). This caused syntax highlighting to fail when I use the nova colorscheme. I did a thorough revamp of my `vimrc` and the plugins I use. I have determined that whenever I execute `colorscheme nova` all of my syntax highlighting goes away. It seems the nova colorscheme plugin isn't working. 

I looked at the latest documentation which says the plugin is now dependent on `sheerun/vim-polyglot`. So I installed that as well, but I still get the same problem—no syntax highlighting at all.

Help!

**Comment by trevordmiller** [comment]
Hi @jlconlin! Thanks for using Nova! I haven't had any other reports of this and everything is working for me and those I know using Nova with Vim - so I'm thinking there might be something up with your setup. Here are a two things to try:

1) Ensure running `vim --version` shows your Vim version is at least 8.0.

2) See if you can reproduce with only this in your `.vimrc`:

```
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'sheerun/vim-polyglot'
Plugin 'trevordmiller/nova-vim'

call vundle#end()
filetype plugin indent on

colorscheme nova
```

Then restart Vim and run: `:PluginClean` and `:PluginInstall` to clean your plugins to only use this minimal config ^

_^ This is a vundle specific version of the example .vimrc from https://trevordmiller.com/projects/nova_

If syntax highlighting works after doing these two things, it means that your issue is related to your other plugins or settings in your `.vimrc` unrelated to Nova. But if you can still reproduce after doing these two things, let me know :)

**Comment by jlconlin** [comment]
I tried your suggestion and it worked using MacVim, but it did not work in my terminal. I generally run with iTerm2 using the terminal vim provided with MacVim. Strange that it works in one place, but not the other.

**Comment by trevordmiller** [comment]
@jlconlin Yeah that is strange. I’m not sure why it wouldn’t be working for you. But I’m happy to try to help debug with you. If you could upload a video or gif of you starting iTerm and then starting Vim and moving around some files that could be helpful in debugging.

**Comment by trevordmiller** [comment]
@jlconlin Also one other idea: do you have anything in `~/.vim/colors`? That directory should be empty.

**Comment by jlconlin** [comment]
After further attempts, it looks like it was some combination with my tmux settings. When I did it outside of tmux then the terminal and gui version worked just fine, but inside of tmux, the terminal version didn't work. 

I am getting syntax highlighting now, but I'm not sure everything is exactly the way it should be—it's kind of hard to see. I'm trying to figure out which of my settings is the culprit.

**Comment by trevordmiller** [comment]
@jlconlin Ok, sounds like you have some personal settings interfering so I'm going to close this issue. The Nova website does have info on how to use tmux: https://trevordmiller.com/projects/nova. You can also check out my own dotfiles as I use iTerm2 + tmux + vim: https://github.com/trevordmiller/dotfiles. If you find anything Nova specific feel free to post a new issue. Thanks!
